'use client';

import { useState } from 'react';
import { ArrowUpRight, Share2, Printer, ChevronDown, Clock3, CarFront, Moon, ArrowRight } from 'lucide-react';
const map=(name:string)=>`https://www.amap.com/search?query=${encodeURIComponent(name)}`;
type Stop={time:string;title:string;duration:string;description:string;place?:string;tip?:string;ticket?:string};
type Day={date:string;title:string;stops:Stop[];stay:string};
type Trip={id:string;number:string;name:string;headline:string;english:string;intro:string;tag:string;drive:string;budget:string;image:string;credit:string;creditUrl:string;route:string[];days:Day[];costs:[string,string][];notes:[string,string][];links:[string,string][]};
const trips:Trip[]=[
{id:'lanxi',number:'01',name:'兰溪人文线',headline:'一城烟火，\n半日闲情。',english:'LANXI / SLOW DAYS',intro:'喝一场清晨的早茶，在古村里找钟池，\n把一家人的中秋，留给江南慢时光。',tag:'古村 · 早茶 · 园林 · 溶洞',drive:'预留 4–5 小时',budget:'2,800',image:'https://www.ourchinastory.com/images/cover/authors/2021/11/normal/%E7%95%B6%E4%BB%A3%E4%B8%AD%E5%9C%8B-%E6%BD%AE%E9%81%8A%E4%B8%89%E5%9C%8B-%E8%AB%B8%E8%91%9B%E5%85%AB%E5%8D%A6%E6%9D%91_x1.jpg',credit:'诸葛八卦村实景 · 当代中国',creditUrl:'https://www.ourchinastory.com/zh/2676',route:['慈溪','兰溪城区','游埠','诸葛村','地下长河','慈溪'],days:[
{date:'09.25 / 周五',title:'先入小城，再逛园林',stops:[
{time:'07:00',title:'慈溪出发',duration:'含休息预留 4–5h',description:'早餐后出发，中途安排一次服务区休息。抵达兰溪先午餐、放行李。',tip:'导航输入酒店或停车场；预计晚到就缩短下午行程。'},
{time:'14:00',title:'芥子园',duration:'1.5–2h',description:'看亭台与借景，给孩子一个小任务：找三种不同的窗。',place:'兰溪 芥子园 横山路11号',tip:'网上开放时间有冲突，前一天致电 0579-88925136 确认。'},
{time:'16:30',title:'兰溪古城 · 晚饭赏月',duration:'1.5–2h',description:'古街慢走，晚餐尝兰溪牛肉面或家常菜；天气好再到开放的江边步道赏月。',place:'兰溪 古城 西门城楼',tip:'19:30 左右回酒店；不额外安排夜间乘船。'}],stay:'连住兰溪城区 2 晚｜优先免费停车、可提供早餐的酒店。'},
{date:'09.26 / 周六',title:'早茶烟火，八卦寻踪',stops:[
{time:'06:15',title:'酒店 → 游埠',duration:'转场预留 45–60min',description:'早餐留给早茶街。自驾到游客停车场，步行进入老街。',place:'兰溪 游埠古镇 停车场'},
{time:'07:00',title:'游埠古镇 · 早茶',duration:'约 2h',description:'肉沉子、鸡子馃、豆浆选几样分着吃；沿溪看老桥与街巷。',place:'兰溪 游埠古镇',tip:'早到为体验早茶，仍可能排队；不执着于一家网红店。'},
{time:'10:00',title:'诸葛八卦村',duration:'约 4h，含午餐',description:'钟池 → 大公堂 → 丞相祠堂 → 古巷。边走边讲诸葛家风，累了就找店坐下。',place:'兰溪 诸葛八卦村 游客中心',ticket:'门票：成人 ¥85 起；儿童/学生 ¥45 起。6周岁（含）以下或身高＜1.2m 免费；以购票页和现场为准。',tip:'游埠转场预留 45–60min。正常购票，不采用“8点前免票”说法。'},
{time:'15:00',title:'回城午休 · 自由晚餐',duration:'留足休息',description:'不再叠加收费景点。下午休息，晚上按体力补逛古街。'}],stay:'继续住原酒店｜行李不挪动，第二天轻装出发。'},
{date:'09.27 / 周日',title:'探一段溶洞，早些回家',stops:[
{time:'08:30',title:'地下长河〔需确认〕',duration:'2–2.5h',description:'退房后前往，先确认开放范围。以溶洞步行为基础，乘船仅在恢复运营后安排。',place:'兰溪 地下长河 游客中心',ticket:'门票：成人 ¥69 起；儿童 ¥37 起。6周岁（含）以下或身高≤1.2m 免费；游船是否恢复须另行确认。',tip:'出发前拨 0579-88258082。若关闭，改古城慢逛并提前返程。'},
{time:'11:30',title:'午餐 · 返程前休息',duration:'约 1h',description:'选返程方向餐馆，吃完休息；把加油、如厕一次完成。'},
{time:'13:00',title:'兰溪 → 慈溪',duration:'预留 4–5h',description:'预计 17:00–18:00 左右抵达，拥堵时顺延。返程前查看实时路况。',place:'慈溪市',tip:'提前返程降低晚高峰重叠概率，不保证避开拥堵。'}],stay:'回到慈溪｜驾驶员疲劳时先休息，不追赶预计到家时间。'}],costs:[['住宿 · 2晚 × ¥450','900'],['餐饮 · 三天一家三口','750'],['油费 / 通行 / 停车','650'],['门票 · 含儿童预留','350'],['机动','150']],notes:[['住宿怎么选','城区连住最省心；想更早喝茶可把第一晚改住游埠，但会多换一次酒店。订前确认三人入住和停车条件。'],['预算怎么理解','¥2,800 是分项规划目标，不是实时套餐价。原预算 ¥2,700–2,900 可作控费目标；另备 ¥300–500 应对中秋房价及票价变化。'],['雨天怎么替换','小雨缩短古街步行；遇强降雨或景区关闭，取消溶洞，改酒店休息、已确认开放的室内场馆或提前返程。'],['亲子提醒','古村石板路、溶洞台阶可能湿滑，穿防滑鞋；不把溶洞作为全程可推婴儿车的路线。']],links:[['兰溪线路 · 文旅部','https://zhuanti.mct.gov.cn/xcss2024_nlhwzzxc/zhejiang/detail/8150.html'],['诸葛村票务与开放参考','https://you.ctrip.com/sight/lanxi611/72172.html'],['芥子园联系方式','https://you.ctrip.com/sight/lanxi611/72194.html'],['地下长河 · 兰溪文旅','https://lxwljt.cn/list_8/13.html'],['7月恢复步行公告转载','https://www.sohu.com/a/1051538111_121123849']]},
{id:'ninghai',number:'02',name:'宁海亲子线',headline:'古镇走走，\n去海边放空。',english:'NINGHAI / FAMILY DAYS',intro:'半天旧时光，半天海风。\n少换酒店、少赶景点，多留一点孩子的时间。',tag:'前童 · 海湾 · 小岛 · 慢游',drive:'预留 2.5–3.5 小时',budget:'2,700',image:'https://dimg04.c-ctrip.com/images/0105k12000a211ir5CC6A_W_600_0_Q90.jpg?proc=autoorient',credit:'横山岛实景 · 携程 / 旅小游',creditUrl:'https://gs.ctrip.com/html5/you/travels/689/4078275.html',route:['慈溪','前童','宁海城区','强蛟 / 横山岛','宁海城区','慈溪'],days:[
{date:'09.25 / 周五',title:'前童古镇，慢慢吃慢慢逛',stops:[
{time:'07:00',title:'慈溪 → 前童',duration:'含休息预留 2.5–3.5h',description:'出门前看路况，服务区安排如厕。计划 10:30 左右开始游览，不赶打卡。',place:'宁海 前童古镇 游客中心'},
{time:'10:30',title:'前童古镇',duration:'3–3.5h，含午餐',description:'沿水巷走走，尝前童三宝：豆腐、香干、空心腐。找石窗、看流水，边吃边逛。',place:'宁海 前童古镇',ticket:'门票：成人 ¥60；儿童/学生 ¥30。6周岁（含）以下或身高≤1.2m 免费；检票需证件。',tip:'豆腐手作须先确认商家和预约，不承诺随到随做。孩子累了就提前结束。'},
{time:'15:00',title:'入住宁海城区 · 午休',duration:'下午自由安排',description:'前童到城区转场预留 30–45min；晚饭选酒店附近，晚上看天气赏月。',place:'宁海县 城区',tip:'室内乐园仅作自选：先确认真实门店、年龄限制和当天营业。'}],stay:'连住宁海城区 2 晚｜选停车方便、有家庭房、离用餐点近的酒店。'},
{date:'09.26 / 周六',title:'海岛与海湾，只安排一次出海',stops:[
{time:'08:00',title:'城区 → 强蛟峡山码头',duration:'转场预留 45–60min',description:'抵达后确认船班、往返票、末班回程及儿童救生衣。',place:'宁海 强蛟 峡山码头',tip:'09:00 为到码头的计划时间，不是已公布或已预订的船班。'},
{time:'09:00',title:'横山岛〔开航后安排〕',duration:'约 3h，含候船往返',description:'乘合规旅游船上岛，走开放步道、看海与树林；体力有限就缩短环岛步行。',place:'宁海 横山岛',ticket:'费用：岛上门票与往返船票须以码头当日售卖为准。历史参考为景区票成人 ¥30 / 儿童 ¥15，船票另计；不写死为当前价。',tip:'不以红树林、赶海或捡贝壳作为必有项目。岛上游览听从现场管理。'},
{time:'12:30',title:'峡山午餐 · 午休',duration:'约 2h',description:'上岸吃海鲜家常菜，先问计价方式。午后找室内歇脚，避开最晒时段。',place:'宁海 强蛟 峡山村'},
{time:'14:30',title:'强蛟岸边慢游',duration:'1–1.5h',description:'在开放岸线看渔船与海湾，喝杯饮品后回酒店；海上牧场只作已核实产品的替换项。',place:'宁海 强蛟镇',tip:'不再安排第二次包船。约 16:30–17:00 回到城区。'}],stay:'继续住原酒店｜如停航，改城区休息与室内活动，不到码头等开航。'},
{date:'09.27 / 周日',title:'睡个好觉，留白半天',stops:[
{time:'09:00',title:'早餐 · 城区自由活动',duration:'约 2h',description:'按孩子状态选酒店活动、阅读或附近短途散步；不再跨城加景点。',tip:'想加室内场馆，先查宁海县发布的博物馆名录，再确认所选场馆当日开放与预约。'},
{time:'11:30',title:'退房 · 午餐',duration:'1–1.5h',description:'收好换洗衣物、玩具和证件，用餐后休息再上高速。'},
{time:'13:00',title:'宁海 → 慈溪',duration:'预留 2.5–3.5h',description:'预计 15:30–16:30 左右到家；遇堵车增加缓冲，路上不再加顺路景点。',place:'慈溪市',tip:'较原计划提前 1 小时启程；真实车程以当天导航为准。'}],stay:'回到慈溪｜适合更看重亲子节奏、愿意给天气留余地的家庭。'}],costs:[['住宿 · 2晚 × ¥450','900'],['餐饮 · 三天一家三口','800'],['油费 / 通行 / 停车','400'],['门票 / 常规往返船票预留','400'],['机动','200']],notes:[['住宿怎么选','县城连住兼顾前童和强蛟；海景房通常增加开支，且不能消除天气对乘船的影响。优先可取消订单。'],['预算怎么理解','¥2,700 是分项规划目标，对应原预算 ¥2,600–2,800。船票预留不含独立包船或船餐套餐；选择这类项目须重新核价，另备 ¥300–500。'],['原方案调整','浙东大峡谷缺少可靠的当前开放确认；“宁海儿童梦工厂”未核实到明确门店，均不列为主行程。海上牧场和横山岛合并为一次海上活动。'],['风雨天怎么替换','出发前 48 小时查天气，前一天向码头确认开航。停航就改城区室内活动或提前返程；不安排浅滩涉水、野路探峡谷。']],links:[['前童开放与票务参考','https://you.ctrip.com/sight/ninghai689/72628.html'],['横山岛景区信息','https://you.ctrip.com/sight/ninghai689/143608.html'],['强蛟休闲渔业 · 发改委','https://www.ndrc.gov.cn/fggz/nyncjj/xczx/202012/t20201214_1252693.html'],['宁海博物馆名录 · 县政府','https://www.ninghai.gov.cn/art/2024/9/23/art_1229705507_59176190.html']]},
{id:'lishui',number:'03',name:'丽水梯田线',headline:'去山里住一晚，\n等一场云海。',english:'LISHUI / TERRACE DAYS',intro:'把赶路留在第一天，\n把清晨、梯田与瓯江，留给一家人慢慢看。',tag:'云海 · 梯田 · 古堰 · 山居',drive:'去程预留 5.5–6.5 小时',budget:'3,800',image:'https://p1-q.mafengwo.net/s13/M00/1C/41/wKgEaVxNUaOAP8-jAA_oOKZ4g1Y80.jpeg?imageMogr2%2Fthumbnail%2F%21600x400r%2Fgravity%2FCenter%2Fcrop%2F%21600x400%2Fquality%2F90',credit:'云和梯田实景 · 马蜂窝',creditUrl:'https://www.mafengwo.cn/poi/5426532.html',route:['慈溪','丽水服务区','云和梯田','崇头镇','古堰画乡','慈溪'],days:[
{date:'09.25 / 周五',title:'一路入山，住进梯田旁',stops:[
{time:'06:30',title:'慈溪 → 云和梯田',duration:'含休息预留 5.5–6.5h',description:'长途驾驶日只安排一次主景区。午餐与加油在高速服务区或云和县城完成，下午再进山。',place:'云和梯田景区 游客中心',tip:'最后一段为山路，天黑前抵达更稳妥；山路不赶时间，儿童容易晕车可备药。'},
{time:'14:30',title:'云和梯田 · 九曲云环',duration:'2–2.5h',description:'从观景台看层层梯田，按体力走短线，不追求走完整个景区。',place:'云和梯田 九曲云环',ticket:'门票参考：成人 ¥70 起；儿童/老人/学生优待票 ¥40 起。索道为自选项目，成人门票+往返索道参考 ¥195 起；以官方售票与现场为准。',tip:'云海、日落受天气影响，不作为必达项目。下雨天路滑，穿防滑鞋。'},
{time:'17:30',title:'崇头镇入住 · 山里晚餐',duration:'傍晚留白',description:'优先订可取消的梯田周边民宿；吃完早点休息，为第二天清晨留体力。',place:'云和县 崇头镇'}],stay:'连住崇头镇或景区周边 2 晚｜核对停车、热水、空调和山路夜间抵达指引。'},
{date:'09.26 / 周六',title:'清晨看梯田，午后到瓯江边',stops:[
{time:'05:45',title:'日出 / 云海〔看天气〕',duration:'1–1.5h',description:'根据天气与民宿位置决定是否出门；阴天也可改为慢早餐，不为拍照透支孩子体力。',place:'云和梯田 白银谷 观景点',tip:'观景台停车和开放安排以景区当天通知为准；清晨温差大，带薄羽绒或冲锋衣。'},
{time:'09:30',title:'坑根石寨 · 梯田慢走',duration:'2h',description:'在村落和梯田边慢走，孩子只走平缓、开放的路段；不走未标识田埂。',place:'云和梯田 坑根石寨',tip:'村内石阶和湿滑路面较多，婴儿车体验一般。'},
{time:'13:00',title:'云和 → 古堰画乡',duration:'预留 2–2.5h',description:'午餐后下山，转场到瓯江边。途中按路况安排休息，不叠加其他收费景点。',place:'丽水 古堰画乡'},
{time:'16:00',title:'古堰画乡 · 瓯江散步',duration:'2h',description:'看通济堰、古樟与江边画乡，时间够再按现场船班体验双程船。',place:'丽水 古堰画乡',ticket:'门票/双程船联票参考：成人 ¥50 左右，儿童/学生 ¥25 左右；6周岁（含）以下或身高≤1.2m 免费。常规门票是否含双程船，以当天售票说明为准。',tip:'景区全年参考开放至 20:30；如果转场晚，只逛江边和画乡一侧，次日不补赶。'}],stay:'继续住崇头镇｜若不想夜走山路，也可把第二晚改住丽水城区，翌日返程更轻松。'},
{date:'09.27 / 周日',title:'睡到自然醒，顺路回慈溪',stops:[
{time:'08:30',title:'早餐 · 整理返程',duration:'约 1.5h',description:'退房前补充饮水、零食和晕车用品；从山里出发时预留足够时间。'},
{time:'10:00',title:'云和 / 丽水 → 慈溪',duration:'预留 5–6h',description:'中途服务区午餐和休息，下午抵达慈溪。车程以当日导航为准。',place:'慈溪市',tip:'返程不加景点；若遇降雨、浓雾或驾驶员疲劳，优先休息或延后出发。'}],stay:'回到慈溪｜这是三条路线中驾驶强度最高的一条，适合愿意为梯田与山居留出体力的家庭。'}],costs:[['住宿 · 山景民宿 2晚','1,300'],['餐饮 · 三天一家三口','850'],['油费 / 通行 / 停车','800'],['门票 · 含儿童预留','500'],['机动','350']],notes:[['住宿怎么选','住崇头镇最省转场，但中秋房价波动大。优先选择可取消订单，并确认停车位置、山路导航和房间保暖。'],['预算怎么理解','¥3,800 为三天两晚规划目标，不含索道、摄影包车和高价民宿升级。选索道或景区内套餐时，另行核价。'],['天气是核心变量','梯田云海与日出都不能保证。出发前48小时看预报；强降雨、低能见度时取消清晨观景，避免在山路赶行程。'],['亲子提醒','梯田边缘、石阶和湿滑山路不适合奔跑。孩子需要全程照看；晕车、保暖和防滑鞋比拍照装备更重要。']],links:[['云和梯田票务参考','https://touch.piao.qunar.com/touch/detail.htm?cat=from_other%3Dt_3928&id=35075'],['古堰画乡官方网站','https://www.lsgyhx.com/index.html'],['古堰画乡开放与优待参考','https://you.ctrip.com/sight/lishui441/56153.html'],['云和梯田导航信息','https://ditu.amap.com/place/B024215MX7']]}
];
function Outside({href,children}:{href:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={14}/></a>}
const spotPhotos:Record<string,{src:string;source:string;label:string}>={
 '芥子园':{src:'https://exp-picture.cdn.bcebos.com/b6f0f0f97fbd4c7c9cb880f6b8bad341027d30a7.jpg?x-bce-process=image%2Fcrop%2Cx_0%2Cy_0%2Cw_750%2Ch_499%2Fformat%2Cf_auto%2Fquality%2Cq_80',source:'https://jingyan.baidu.com/article/c910274bb8d25d8c371d2d0a.html',label:'芥子园入口'},
 '游埠古镇 · 早茶':{src:'https://cs.zjol.com.cn/jms/202210/W020221026516785570301.png',source:'https://cs.zjol.com.cn/jms/202210/t20221026_24967547.shtml',label:'游埠早茶街'},
 '诸葛八卦村':{src:'https://www.ourchinastory.com/images/cover/authors/2021/11/normal/%E7%95%B6%E4%BB%A3%E4%B8%AD%E5%9C%8B-%E6%BD%AE%E9%81%8A%E4%B8%89%E5%9C%8B-%E8%AB%B8%E8%91%9B%E5%85%AB%E5%8D%A6%E6%9D%91_x1.jpg',source:'https://www.ourchinastory.com/zh/2676',label:'诸葛八卦村'},
 '地下长河〔需确认〕':{src:'https://zhuanti.mct.gov.cn/Uploads/Picture/2021/05/14/u609e2e692f00b.jpg',source:'https://zhuanti.mct.gov.cn/zj_detail/407.html',label:'地下长河溶洞'},
 '前童古镇':{src:'https://boot-img.xuexi.cn/image/1005/process/b16a31617ddf46d5b6933a7a685e1e06.jpg',source:'https://www.whw.kim/?a=index&aid=22553&c=View&m=home',label:'前童古镇水巷'},
 '横山岛〔开航后安排〕':{src:'https://dimg04.c-ctrip.com/images/0105k12000a211ir5CC6A_W_600_0_Q90.jpg?proc=autoorient',source:'https://gs.ctrip.com/html5/you/travels/689/4078275.html',label:'横山岛'},
 '强蛟岸边慢游':{src:'https://epaper.cnnb.com.cn/nbrb/pc/pic/202505/03/b39aac31-795a-41ba-a6fe-f9d44d70f7f9.jpg.1',source:'https://epaper.cnnb.com.cn/nbrb/pc/content/202505/03/content_211756.html',label:'宁海强蛟镇'},
 '云和梯田 · 九曲云环':{src:'https://p1-q.mafengwo.net/s13/M00/1C/41/wKgEaVxNUaOAP8-jAA_oOKZ4g1Y80.jpeg?imageMogr2%2Fthumbnail%2F%21600x400r%2Fgravity%2FCenter%2Fcrop%2F%21600x400%2Fquality%2F90',source:'https://www.mafengwo.cn/poi/5426532.html',label:'云和梯田'},
 '古堰画乡 · 瓯江散步':{src:'https://dimg04.c-ctrip.com/images/0106u1200098drdqfCA75_W_600_0_Q90.jpg',source:'https://you.ctrip.com/sight/lishui441/56153.html',label:'古堰画乡'}
};
function Poster({trip}:{trip:Trip}){return <article className={`poster ${trip.id}`}>
<header className="poster-heading"><span>中秋出走三日 <span className="thin">/ 慈溪出发</span></span><span className="edition">路线 {trip.number} · 2026</span></header>
<div className="hero"><figure><img src={trip.image} alt={trip.credit} referrerPolicy="no-referrer"/><figcaption><Outside href={trip.creditUrl}>{trip.credit}</Outside></figcaption></figure><div className="hero-copy"><span className="eyebrow">{trip.english}</span><h1>{trip.headline}</h1><p>{trip.intro}</p><span className="hero-tag">{trip.tag}</span><div className="hero-index">{trip.number}<span>/ 02</span></div></div></div>
<div className="summary-strip"><div><Moon/><span>两大一小 · 三天两晚<strong>9月25日 — 27日</strong></span></div><div><CarFront/><span>慈溪出发 · 去程计划<strong>{trip.drive}</strong></span></div><div className="price"><span>全家规划预算</span><strong>¥{trip.budget}<small>左右</small></strong></div></div>
<div className="route-line"><span className="eyebrow">路线顺序</span><div>{trip.route.map((p,i)=><span key={i}>{p}{i<trip.route.length-1&&<ArrowRight size={13}/>}</span>)}</div></div>
<div className="section-title"><h2>三天，刚刚好的安排</h2><span>点击地点打开地图 · 展开查看提醒</span></div>
<div className="days">{trip.days.map((day,i)=><section className="day" key={day.date}><div className="day-label"><span>DAY <b>0{i+1}</b></span><small>{day.date}</small></div><h3>{day.title}</h3><div className="stops">{day.stops.map(stop=>{const photo=spotPhotos[stop.title];return <div className="stop" key={stop.time}><time>{stop.time}</time><div><div className="stop-title">{stop.place?<Outside href={map(stop.place)}>{stop.title}</Outside>:<strong>{stop.title}</strong>}</div><span className="duration"><Clock3 size={12}/>{stop.duration}</span><p>{stop.description}</p>{stop.ticket&&<p className="ticket">{stop.ticket}</p>}{stop.tip&&<details className="tip"><summary>出行提醒<ChevronDown size={13}/></summary><p>{stop.tip}</p></details>}{photo&&<details className="spot-photo"><summary>查看景点实景<ChevronDown size={13}/></summary><figure><img src={photo.src} alt={photo.label} referrerPolicy="no-referrer"/><figcaption><Outside href={photo.source}>{photo.label} · 图片来源</Outside></figcaption></figure></details>}</div></div>})}</div><p className="stay"><Moon size={15}/>{day.stay}</p></section>)}</div>
<div className="bottom-grid"><section className="budget"><div className="section-title"><h2>一家三口，预算摊开看</h2><span>规划分配 / 非实时报价</span></div><div className="costs">{trip.costs.map(([label,value])=><div key={label}><span>{label}</span><strong>¥{value}</strong></div>)}</div><p className="small-note">按自有车辆、1间房住2晚估算；儿童年龄与身高未提供，门票按预留额计，不默认免票。交通已预留通行费；不含购物和车辆折旧。</p></section><section className="essentials"><h2>出发前，留意这几件事</h2>{trip.notes.map(([title,body])=><details key={title}><summary>{title}<ChevronDown size={16}/></summary><p>{body}</p></details>)}</section></div>
<footer className="poster-footer"><div><span className="eyebrow">PACK LIGHT, TRAVEL SLOW</span><p>证件 · 防滑鞋 · 薄外套 · 雨具 · 饮水 · 换洗衣物 · 儿童安全座椅</p></div><strong>{trip.name}<span> / {trip.number}</span></strong></footer>
<details className="references"><summary>资料来源、实景图片与核实说明<ChevronDown size={16}/></summary><div className="reference-links">{trip.links.map(([label,link])=><Outside key={label} href={link}>{label}</Outside>)}<Outside href={trip.creditUrl}>主图原始页面</Outside><Outside href={`https://www.bing.com/images/search?q=${encodeURIComponent(trip.id==='lanxi'?'游埠古镇 芥子园 地下长河 实景':'宁海 前童古镇 强蛟 横山岛 实景')}`}>查看更多景点实景</Outside></div><p>资料核查：2026年9月6日。日期暂按2026年中秋规划；所有时点是建议安排，车程为含休息的规划预留，未接入实时导航。营业、票务、船班、天气须在临行前再次确认。实景图来自外部来源，非本次实拍，版权归原权利人；未取得另行复用授权，页面保留来源链接。</p></details>
</article>}
export default function PosterClient(){const[message,setMessage]=useState('');const[selected,setSelected]=useState('lanxi');const subtitles:Record<string,string>={lanxi:'早茶与古村',ninghai:'古镇与海风',lishui:'云海与梯田'};async function share(){try{const url=window.location.href;if(navigator.share){await navigator.share({title:'中秋出走三日｜慈溪出发',url});}else{await navigator.clipboard.writeText(url);setMessage('链接已复制，可以发给同行的人。');}}catch{setMessage('可复制浏览器地址栏中的链接分享。');}}return <main><nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">秋</span>周末之外<span className="brand-sub">三日自驾手册</span></a><div className="toolbar"><button onClick={()=>window.print()}><Printer size={16}/><span>打印 / 存 PDF</span></button><button onClick={share}><Share2 size={16}/><span>分享</span></button></div></nav><div className="intro" id="top"><div><span className="eyebrow">MID-AUTUMN GETAWAY</span><h2>这个中秋，一起出发。</h2><p>从宁波慈溪出发，三条路线选一条。<a href="https://www.sioc.cas.cn/news/tzgg/202608/t20260826_8265438.html" target="_blank" rel="noreferrer">2026.09.25 — 09.27</a></p></div><span className="intro-note">两大一小 / 3 DAYS<br/>把行程放慢一点。</span></div><p className="share-message" role="status">{message}</p><div className="trip-tabs"><div className="trip-picker" role="tablist" aria-label="路线选择">{trips.map(trip=><button key={trip.id} type="button" role="tab" aria-selected={selected===trip.id} className={selected===trip.id?'is-active':''} onClick={()=>setSelected(trip.id)}><span>{trip.number}</span>{trip.name}<small>{subtitles[trip.id]}</small></button>)}</div>{trips.map(trip=><div key={trip.id} role="tabpanel" hidden={selected!==trip.id}><Poster trip={trip}/></div>)}</div><div className="endnote">没有“保证不堵”的时间表。提前出门、少换酒店、每天留白，才是三天过得舒服的关键。</div></main>}
